package kernels

import (
       "bytes"
)

func GenMergedKernelSource() string {
     KernelsSource := bytes.NewBufferString(ConstantsHeader)
     KernelsSource.WriteString(ConstantsHeader)
     KernelsSource.WriteString(StdintHeader)
     KernelsSource.WriteString(CLRNG_Header)
     KernelsSource.WriteString(CLProbDist_Header)
     KernelsSource.WriteString(StencilHeader)
     KernelsSource.WriteString(Float3Header)
     KernelsSource.WriteString(ExchangeHeader)
     KernelsSource.WriteString(AtomicFHeader)
     KernelsSource.WriteString(ReduceHeader)
     KernelsSource.WriteString(SumHeader)
     KernelsSource.WriteString(AddCubicAnisotropySource)
     KernelsSource.WriteString(CropSource)
     KernelsSource.WriteString(DmiBulkSource)
     KernelsSource.WriteString(DmiSource)
     KernelsSource.WriteString(DivideSource)
     KernelsSource.WriteString(DotProductSource)
     KernelsSource.WriteString(ExchangeSource)
     KernelsSource.WriteString(ExchangeDecodeSource)
     KernelsSource.WriteString(KernMulCSource)
     KernelsSource.WriteString(KernMulRSymm2DxySource)
     KernelsSource.WriteString(KernMulRSymm2DzSource)
     KernelsSource.WriteString(KernMulRSymm3DSource)
     KernelsSource.WriteString(LLNoPrecessSource)
     KernelsSource.WriteString(LLTorqueSource)
     KernelsSource.WriteString(MAdd2Source)
     KernelsSource.WriteString(MAdd3Source)
     KernelsSource.WriteString(ReduceDotSource)
     KernelsSource.WriteString(ReduceMaxAbsSource)
     KernelsSource.WriteString(ReduceMaxDiffSource)
     KernelsSource.WriteString(ReduceMaxVecDiff2Source)
     KernelsSource.WriteString(ReduceMaxVecNorm2Source)
     KernelsSource.WriteString(ReduceSumSource)
     KernelsSource.WriteString(RegionAddVSource)
     KernelsSource.WriteString(RegionDecodeSource)
     KernelsSource.WriteString(RegionSelectSource)
     KernelsSource.WriteString(ResizeSource)
     KernelsSource.WriteString(ShiftBytesSource)
     KernelsSource.WriteString(ShiftXSource)
     KernelsSource.WriteString(SlonczewskiSource)
     KernelsSource.WriteString(TemperatureSource)
     KernelsSource.WriteString(TopologicalChargeSource)
     KernelsSource.WriteString(UniaxialAnisotropySource)
     KernelsSource.WriteString(VecNormSource)
     KernelsSource.WriteString(ZeroMaskSource)
     KernelsSource.WriteString(ZhangLiSource)
     KernelsSource.WriteString(SquareSource)
     return KernelsSource.String()
}
